config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get "/menus_overview", to: 'static_pages#menus_overview'
  get "/staff", to: 'static_pages#staff'
  get "/map", to: 'static_pages#map'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    omniauth_callbacks: "omniauth_callbacks"
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  resources :users do 

    member do # memberは:idあり
      # GET	/users/:id/edit_event_response
      get "edit_event_response"
      patch "update_event_response"
      delete "destroy_event_response"
      patch "update_request_status"
      # GET	/users/:id/admin_top
      get "admin_top"
      resources :menus
      # GET	/users/:id/admin_events
      get "admin_events"
      get "edit_admin_event_response"
      patch "update_admin_event_response"
      delete "destroy_admin_event_response"
      patch "update_admin_request_status"
    end
    resources :events, except: :show do
      collection do # collectionはevent idなし
        # GET /users/:user_id/events/edit_account_info
        get "edit_account_info"
        # PATCH /users/:user_id/events/update_account_info
        patch "update_account_info"
      end
    end

  end

  
  
end

app/models/menu.rb
class Menu < ApplicationRecord

  def view_item_and_price
    self.item + ' (税込' + self.price.to_s + '円)'
  end

end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :current_user_admin?
  
  def index
    @menus = Menu.all
  end

  def show
    @menu = Menu.find(params[:id])
  end

  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.find(params[:id])
    @menu = Menu.create!(menu_params)
    flash[:success] = "新規メニューの作成に成功しました"
    redirect_to menus_path(current_user) and return
  rescue
    flash[:danger] = "新規メニューの作成に問題がありました"
    redirect_to menus_path(current_user) and return
  end

  def edit
    @menu = Menu.find(params[:id])
  end

  def update
    @menu = Menu.find(params[:id])
    if @menu.update_attributes!(menu_params)
      flash[:success] = "メニュー情報の更新に成功しました。"
     redirect_to menus_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    menu = Menu.find(params[:id])
    menu.destroy
    flash[:success] = "メニューを削除しました。"
    redirect_to menus_path(current_user)
  end

  private
  
  def menu_params
    params.require(:menu).permit(:item, :item_number, :price, :description)
  end

end

app/helpers/menus_helper.rb
module MenusHelper
end

app/views/menus/_edit.html.erb
<div class="modal-dialog modal-md modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>



<h1 class="modal-title">メニュー編集</h1>
<div class="modal-body">
<div class="container">
  
    <%= form_with(model: @menu, url: menu_path(current_user, @menu), local: true) do |f| %>
      <div class="form-group">
        <%= f.label :item_number %>
        <%= f.number_field :item_number, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :item %>
        <%= f.text_field :item, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :price %>
        <%= f.number_field :price, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      
      <%= f.submit "編集", class: "btn btn-md btn-primary" %>
      <%= link_to 'キャンセル', menus_path(current_user), class: "btn btn-md btn-info" %>
      
    <% end %>
</div>
</div>
</div>
</div>
</div>

app/views/menus/_new.html.erb
<div class="modal-dialog modal-md modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>



<h1 class="modal-title">新規メニュー作成</h1>
<div class="modal-body">
<div class="container">
  
    <%= form_with(model: @menu, url: menus_path(current_user, @menu), local: true) do |f| %>
      <div class="form-group">
        <%= f.label :item_number %>
        <%= f.number_field :item_number, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :item %>
        <%= f.text_field :item, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :price %>
        <%= f.number_field :price, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
      
      <%= f.submit "新規作成", class: "btn btn-md btn-primary" %>
      <%= link_to 'キャンセル', menus_path(current_user), class: "btn btn-md btn-info" %>
      
    <% end %>
</div>
</div>
</div>
</div>
</div>

app/views/menus/edit.js.erb
$("#menu-edit").html("<%= escape_javascript(render 'edit') %>");
$("#menu-edit").modal("show");

app/views/menus/index.html.erb
<h1>管理者専用ページ</h1>

<div class="container">
<%= link_to '<<管理者専用トップページに戻る', admin_top_user_path(current_user), style: "font-size:16px;" %>
<br><p></p>
<%= link_to 'メニュー新規作成', new_menu_path, remote: true, class: "btn btn-md btn-primary" %>
<p class='center'>【メニュー&料金一覧】</p>
<table class="table table-bordered table-condensed table-hover">
  <thead>
    <tr class="table-head-1">
      <th class="center">サービス番号</th>
      <th class="center">サービス名</th>
      <th class="center">税込価格</th>
      <th class="center">編集</th>
      <th class="center">削除</th>
    </tr>
  </thead>
  <% @menus.each do |menu| %>
    <tbody>
      <tr class="center table-account">
        <td><%= menu.item_number %></td>
        <td><%= link_to menu.item, menu_path(menu) %></td>
        <td>¥<%= menu.price.to_s(:delimited) %></td>
        <td><%= link_to '編集', edit_menu_path(menu), remote: true, class: "btn btn-xs btn-primary" %></td>
        <td><%= link_to '削除', menu_path(menu), method: :delete, data: { confirm: "メニューを削除しますか?" }, class: "btn btn-xs btn-danger" %></td>
      </tr>
    </tbody>
  <% end %>
</table>
    <p>　　　　　</p>
    <p>　　　　　</p>
    <p>　　　　　</p>
</div>

<div id="menu-new" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="menu-edit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/menus/new.js.erb
$("#menu-new").html("<%= escape_javascript(render 'new') %>");
$("#menu-new").modal("show");

app/views/menus/show.html.erb
<h1>管理者専用ページ</h1>

<div class="container">
<%= link_to '<<メニュー&料金一覧に戻る', menus_path(current_user), style: "font-size: 16px;" %>
<p class="center">【メニュー詳細】</p>
<table class="table table-bordered table-condensed table-striped table-account">
  <thead>
    <tr>
      <th class="table-head-1">サービス番号</th>
      <th class="table-head-1">サービス名</th>
      <th class="table-head-1">税込価格</th>
      
    </tr>
  </thead>
  <tbody>
    <tr class="center">
      <td><%= @menu.item_number %></td>
      <td><%= @menu.item %></td>
      <td><%= @menu.price.to_s(:delimited) %></td>
      
    </tr>
  </tbody>
  <thead><tr><th colspan="3" class="table-head-1">詳細</th></tr></thead>
  <tbody><tr><td class="center" colspan="3"><%= @menu.description %></td></tr></tbody>
</table>
</div>