config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get "/menus_overview", to: 'static_pages#menus_overview'
  get "/staff", to: 'static_pages#staff'
  get "/map", to: 'static_pages#map'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    omniauth_callbacks: "omniauth_callbacks"
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  resources :users do 

    member do # memberは:idあり
      # GET	/users/:id/edit_event_response
      get "edit_event_response"
      patch "update_event_response"
      delete "destroy_event_response"
      patch "update_request_status"
      # GET	/users/:id/admin_top
      get "admin_top"
      resources :menus
      # GET	/users/:id/admin_events
      get "admin_events"
      get "edit_admin_event_response"
      patch "update_admin_event_response"
      delete "destroy_admin_event_response"
      patch "update_admin_request_status"
    end
    resources :events, except: :show do
      collection do # collectionはevent idなし
        # GET /users/:user_id/events/edit_account_info
        get "edit_account_info"
        # PATCH /users/:user_id/events/update_account_info
        patch "update_account_info"
      end
    end

  end

  
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[line]

  before_save { self.email = email.downcase }

  validates :name, length: { maximum: 30 }
  validates :phone, length: { maximum: 20 }
  validates :address, length: { maximum: 100 }


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true

  # 以下を追加
  def social_profile(provider)
    social_profiles.select { |sp| sp.provider == provider.to_s }.first
  end

  def set_values(omniauth)
    return if provider.to_s != omniauth["provider"].to_s || uid != omniauth["uid"]
    credentials = omniauth["credentials"]
    info = omniauth["info"]

    access_token = credentials["refresh_token"]
    access_secret = credentials["secret"]
    credentials = credentials.to_json
    name = info["name"]
    # self.set_values_by_raw_info(omniauth['extra']['raw_info'])
  end

  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    self.save!
  end
  # 以上を追加

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    # super
    current_user.update_attributes!(user_params)
    flash[:success] = "ユーザー情報を更新しました"
    if current_user.staff? || current_user.admin?
      redirect_to user_path(current_user) and return
    else
      redirect_to user_events_path(current_user) and return
    end
  rescue
    flash[:danger] = "ユーザー情報の更新に問題がありました"
    redirect_to root_url and return
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #    super
  # end

  # POST /resource/sign_in
  def create
    # redirect_to XXXXXX(current_user) 必ずcurrent_userを書くこと。
    # current_userにidが格納されている。paramsにはidが含まれない。
    if current_user.admin?
      redirect_to admin_top_user_path(current_user)
    elsif current_user.staff?
      redirect_to user_path(current_user)
    else
      redirect_to user_events_path(current_user)
    end
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

    # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :current_user_admin?, only: [:index, :admin_top, :admin_events]
  
  

  def show # スタッフの業務管理ページ
    @user = User.find(params[:id])
    
    @users = User.joins(:events).group("users.id").order(name: :asc).where("started_at >= ?", Date.today)
    @events = Event.where("started_at >= ?", Date.today).order(started_at: :asc)
    
    if !current_user.admin?
      redirect_to root_url unless @user == current_user
    end
  end

  def index
    @user = User.find_by(params[:id])
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.find(params[:id])
    @user = User.create!(user_params)
    flash[:success] = "新規ユーザーの作成に成功しました"
    redirect_to users_path(current_user) and return
  rescue
    flash[:danger] = "ユーザー情報の作成に問題がありました"
    redirect_to users_path(current_user) and return
  end

  def edit
    
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes!(user_params)
    flash[:success] = "ユーザー情報を更新しました"
    redirect_to user_path(@user) and return
  rescue
    flash[:danger] = "ユーザー情報の更新に問題がありました"
    redirect_to user_path(@user) and return
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:success] = "ユーザーを削除しました。"
    redirect_to users_path(current_user)
  end

  def edit_event_response
    @event = Event.find(params[:format]) 
    @menus = Menu.all
    @users = User.where(staff: true).where.not(admin: true) # 担当者全員
  end

  def update_event_response
    
    event = Event.find(params[:id])
    if event.update_attributes(event_params)
      flash[:success] = "お客様リクエストを更新しました"
      redirect_to user_path(current_user)
    else
      flash[:danger] = "お客様リクエストの更新に失敗しました"
      render 'edit_event_response_user_path(current_user)'
    end
  end

  def destroy_event_response
    
    event = Event.find(params[:format]) # paramsにidが入っているので、それを取得してローカル変数に代入する
    event.destroy # ローカル変数に入ったオブジェクトを削除する
    flash[:success] = "予約リクエストを削除しました。"
    redirect_to user_path(current_user)
  end

  def update_request_status
    
    event = Event.find(params[:format])
    if event.update_attributes(event_status_params)
      flash[:success] = "お客様リクエストを更新しました"
      redirect_to user_path(current_user)
    else
    flash[:danger] = "お客様リクエストの更新に失敗しました"
    render "user_path(current_user)"
    end
  end

  def admin_top
  end

  def admin_events
    @present_users = User.joins(:events).group("users.id").order(name: :asc).where("started_at >= ?", Date.today)
    @past_users = User.joins(:events).group("users.id").order(name: :asc).where("started_at < ?", Date.today)

    @present_events = Event.where("started_at >= ?", Date.today).order(started_at: :asc)
    @past_events = Event.where("started_at < ?", Date.today).order(started_at: :asc)
  end

  def edit_admin_event_response
    @event = Event.find(params[:format]) 
    @menus = Menu.all
    @users = User.where(staff: true).where.not(admin: true) # 担当者全員
  end

  def update_admin_event_response
    event = Event.find(params[:id])
    if event.update_attributes(event_params)
      flash[:success] = "お客様リクエストを更新しました"
      redirect_to admin_events_user_path(current_user)
    else
      flash[:danger] = "お客様リクエストの更新に失敗しました"
      render 'edit_admin_event_response_user_path(current_user)'
    end
  end

  def destroy_admin_event_response
    event = Event.find(params[:format])
    event.destroy
    flash[:success] = "予約リクエストを削除しました。"
    redirect_to admin_events_user_path(current_user)
  end

  def update_admin_request_status
    
    event = Event.find(params[:format])
    if event.update_attributes(event_status_params)
      flash[:success] = "お客様リクエストを更新しました"
      redirect_to admin_events_user_path(current_user)
    else
    flash[:danger] = "お客様リクエストの更新に失敗しました"
    render "admin_events_user_path(current_user)"
    end
  end


  def user_event_new
    @event = Event.new
  end

  def user_event_create
    
    @user = User.find_by(control_number: params[:user][:control_number])
    @event = Event.new(event_params)

    @event.save!
    flash[:success] = "新規予約リクエストの作成に成功しました"
    redirect_to user_path(current_user) and return
  rescue
    flash[:danger] = "新規予約リクエストの作成に失敗しました"
    redirect_to user_path(current_user) and return
  end

  

  private

  def event_status_params
    params.permit(:status_event_request)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit.html.erb
<div class="modal-dialog modal-md modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>


<h1 class="modal-title">ユーザー情報の編集</h1>
<div class="modal-body">
<div class="container">
  
    <%= form_with(model: @user, url: user_path(@user), local: true) do |f| %>
      <div class="form-group">
        <%= f.label :control_number %>
        <%= f.number_field :control_number, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :phone %>
        <%= f.text_field :phone, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class: "form-control" %>
      </div>
      
      <%= f.submit "変更", class: "btn btn-md btn-primary" %>
      <%= link_to 'キャンセル', user_path(@user), class: "btn btn-md btn-info" %>
      
    <% end %>
</div>
</div>
</div>
</div>
</div>

app/views/users/_edit_admin_event_response.html.erb
<div class="modal-dialog modal-md modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>

      <h1 class="modal-title">ご予約の変更</h1>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= form_with(model: @event, url: update_admin_event_response_user_path(@event), local: true, method: :patch) do |f| %>
                
              <%= f.label :title %>
              <%= f.collection_select :title, @menus, :view_item_and_price, :view_item_and_price, class: "form-control" %><br>

              <%= f.label :started_at %>
              <%= f.datetime_select :started_at, { minute_step: 30, start_hour: 9, end_hour: 18 } %>
              <%= f.label :selector_stylist_request %>
              <%= f.collection_select :selector_stylist_request, @users, :name, :name, { include_blank:"希望なし" }, { class: "form-control" } %>
              <%#= f.hidden_field :status_event_request, value: "リクエスト中" %>
              <%= f.label :note %>
              <%= f.text_area :note, class: "form-control" %>
            
              <%= f.submit "変更", class: "btn btn-md btn-primary" %>
        
              <button type="button" class="btn btn-default btn-info %>" data-dismiss="modal">
                    キャンセル
              </button>
            <% end %>
          </div>
        </div>
      </div>


    </div>
  </div>
</div>

app/views/users/_edit_event_response.html.erb
<div class="modal-dialog modal-md modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>

      <h1 class="modal-title">ご予約の変更</h1>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= form_with(model: @event, url: update_event_response_user_path(@event), local: true, method: :patch) do |f| %>
                
              <%= f.label :title %>
              <%= f.select :title, [['カット、シャンプー(¥3,800税込)'], ['カット、シャンプー、パーマ(¥9,800税込)'], ['縮毛矯正(¥4,800税込)'], ['着付け(¥5,800税込)']], { include_blank: true }, class: "form-control" %>

              <%= f.label :started_at %>
              <%= f.datetime_select :started_at, { minute_step: 30, start_hour: 9, end_hour: 18 } %>
              <%= f.label :selector_stylist_request %>
              <%= f.select :selector_stylist_request, [['希望なし'], ['担当者1'], ['担当者2'], ['担当者3']], { include_blank: true }, { class: "form-control" } %>
              <%#= f.hidden_field :status_event_request, value: "リクエスト中" %>
              <%= f.label :note %>
              <%= f.text_area :note, class: "form-control" %>
            
              <%= f.submit "変更", class: "btn btn-md btn-primary" %>
        
              <button type="button" class="btn btn-default btn-info %>" data-dismiss="modal">
                    キャンセル
              </button>
            <% end %>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/users/admin_events.html.erb
<h1>管理者専用ページ</h1>

<div class="container">
  <%= link_to '<<管理者専用トップページに戻る', admin_top_user_path(current_user), style: "font-size:16px;" %>
  <p class="center" style="font-size:20px;">【現在のご予約リクエスト】</p>
    <% @present_users.each do |user| %>
      <table class="table table-bordered table-condensed table-account">
        <thead>
          <tr><th colspan="6" class="table-head-2"><%= user.name %> さまからのご予約 [Email: <%= mail_to user.email %> ] [電話番号: <%= user.phone %> ]</th></tr>
        </thead>
        <% @present_events.each do |event| %>
          <% if event.user_id == user.id %> <%# これでeventのなかで該当するuserのeventだけを表示する  %>
            <thead>  
              <tr><th colspan="6" class="table-margin"></th></tr>
              <tr> 
                <th class="table-head-1">ご希望の時間</th>
                <th class="table-head-1">ご希望の内容</th>
                <th class="table-head-1">ご希望のスタイリスト</th>
                <th class="table-head-1">変更</th>
                <th class="table-head-1">削除</th>
                <th class="center" style="background-color: #FFFF00;">リクエスト状況</th>
              </tr>
            </thead>
            <tbody>
              <tr> 
                <td class="center"><%= l(event.started_at, format: :custom) %></td>
                <td class="center"><%= event.title %></td>
                <td class="center"><%= event.selector_stylist_request %></td>
                <td class="center"><%= link_to '変更', edit_admin_event_response_user_path(user, event), remote: true, class: "btn btn-xs btn-primary" %></td>
                <td class="center"><%= link_to '削除', destroy_admin_event_response_user_path(user, event), method: :delete, data: { confirm: '削除してもよろしいでしょうか?' }, class: "btn btn-xs btn-info" %></td>
                <td class="center" style="color: #F00; font-weight: 900;"><%= event.status_event_request %></td>
              </tr>
              <tr>
                <th colspan="5" class="table-head-1">ご要望/通信欄</th>
                <th class="table-head-1">リクエスト状況の更新</th>
              </tr>
              <tr>
                <td colspan="5"  class="center"><%= event.note %></td>
                <td class="center">
                  <%= form_with(model: @event, url: update_admin_request_status_user_path(user, event), method: :patch, local: true) do |f| %>
                    <%= f.select :status_event_request, [['現在リクエスト中'], ['予約受付完了/予約済み'],['内容の変更が必要'], ['保留中'], ['キャンセル完了/取消済み']], { include_blank: true } %>
                    <%= f.submit "更新", class: "btn btn-xs btn-danger" %>
                  <% end %>
                </td>
              </tr>
            </tbody>
          <% end %>
        <% end %>
      </table>
    <% end %>

  <p>　　　　　</p>

  <p class="center" style="font-size:20px;">【過去のご予約リクエスト履歴】</p>
    <% @past_users.each do |user| %>
      <table class="table table-condensed table-bordered table-account">
        <thead>
          <tr><th colspan="6" class="table-head-4"><%= user.name %> さまからのご予約 [Email: <%= mail_to user.email %> ] [電話番号: <%= user.phone %> ]</th></tr>
        </thead>
        <% @past_events.each do |event| %>
          <% if event.user_id == user.id %> <%# これでeventのなかで該当するuserのeventだけを表示する  %>
            <thead>
              <tr><th colspan="6" class="table-margin"></th></tr>
              <tr> 
                <th class="table-head-1">ご希望の時間</th>
                <th class="table-head-1">ご希望の内容</th>
                <th class="table-head-1">ご希望のスタイリスト</th>
                <th class="table-head-1">変更</th>
                <th class="table-head-1">削除</th>
                <th class="center table-head-1">リクエスト状況</th>
              </tr>
            </thead>
            <tbody>
              <tr> 
                <td class="center"><%= l(event.started_at, format: :custom) %></td>
                <td class="center"><%= event.title %></td>
                <td class="center"><%= event.selector_stylist_request %></td>
                <td class="center"><%= link_to '変更', edit_admin_event_response_user_path(user, event), remote: true, class: "btn btn-xs btn-primary" %></td>
                <td class="center"><%= link_to '削除', destroy_admin_event_response_user_path(user, event), method: :delete, data: { confirm: '削除してもよろしいでしょうか?' }, class: "btn btn-xs btn-info" %></td>
                <td class="center" style="font-weight: 900;"><%= event.status_event_request %></td>
              </tr>
              <tr>
                <th colspan="5" class="table-head-1">ご要望/通信欄</th>
                <th class="table-head-1">リクエスト状況の更新</th>
              </tr>
              <td colspan="5"  class="center"><%= event.note %></td>
              <td class="center">
                <%= form_with(model: @event, url: update_admin_request_status_user_path(user, event), method: :patch, local: true) do |f| %>
                    <%= f.select :status_event_request, [['現在リクエスト中'], ['予約受付完了/予約済み'],['内容の変更が必要'], ['保留中'], ['キャンセル完了/取消済み']], { include_blank: true } %>
                    <%= f.submit "更新", class: "btn btn-xs btn-danger" %>
                  <% end %>
              </td>
            </tbody>
          <% end %>
        <% end %>
      </table>
    <% end %>
</div>

<div id="edit-admin-event-response" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/admin_top.html.erb
<h1>管理者専用ページ</h1>
  <p class="center">【管理者専用トップページ】</p>
<ul class="box flexbox">
  <li class="radius-square-admin radious-square-bg1">
    <p><%= link_to 'ユーザー情報', users_path, class: "btn btn-lg btn-primary" %></p>
    <p>・管理者情報</p>
    <p>・スタッフ情報</p>
    <p>・お客様情報</p>
    <p>確認/修正/削除</p>
  </li>  
  <li class="radius-square-admin radious-square-bg3">
    <p><%= link_to 'ご予約情報', admin_events_user_path, class: "btn btn-lg btn-primary" %></p>
    <p>・ご予約日時</p>
    <p>・ご予約者名</p>
    <p>・ご予約内容</p>
    <p>確認/修正/削除</p>
  </li>
  <li class="radius-square-admin radious-square-bg2">
    <p><%= link_to 'メニュー&料金情報', menus_path, class: "btn btn-lg btn-primary" %></p>
    <p>・メニュー</p>
    <p>・料金</p>
    <p>・サービス詳細</p>
    <p>確認/修正/削除</p>
  </li>
</ul>
  

app/views/users/edit.js.erb
$("#user-edit").html("<%= escape_javascript(render 'edit') %>");
$("#user-edit").modal("show");

app/views/users/edit_admin_event_response.js.erb
$("#edit-admin-event-response").html("<%= escape_javascript(render 'edit_admin_event_response') %>");
$("#edit-admin-event-response").modal("show");

app/views/users/edit_event_response.js.erb
$("#user-edit-event-response").html("<%= escape_javascript(render 'edit_event_response') %>");
$("#user-edit-event-response").modal("show");

app/views/users/show.html.erb
<% if current_user.admin? %>
  <h1>管理者専用ページ</h1>
<% else %>
  <h1>スタッフ専用ページ</h1>
<% end %>

<div>
  <% if current_user.admin? %>
    <%= link_to '<<ユーザー一覧に戻る', users_path, style: "font-size:16px;" %>
  <% end %>

  <p class="center">【<%= @user.name%>さんのアカウント情報】</p>
  <table class="table table-bordered table-condensed table-striped table-account">
    <thead>
      <tr>
        <th class="table-head-3">管理番号</th>
        <th class="table-head-3">名前</th>
        <th class="table-head-3">Email</th>
        <th class="table-head-3">電話番号</th>
        <th class="table-head-3">変更</th>
      </tr>
    </thead>
    <tbody>
      <tr class="center">
        <td><%= @user.control_number %></td>
        <td><%= @user.name %></td>
        <td><%= mail_to @user.email %></td>
        <td><%= @user.phone %></td>
        <% if current_user.admin? %>
          <td><%= link_to '管理者変更', edit_user_path(@user), remote: true, class: "btn btn-xs btn-danger" %></td>
        <% else %>
          <td><%= link_to '変更', edit_user_registration_path(@user), local: true, class: "btn btn-xs btn-primary" %></td>
        <% end %>
      </tr>
    </tbody>
      <th class="table-head-3">住所</th>
      <td colspan="4" class="center"><%= @user.address %></td>
  </table>

  <% if !current_user.admin? %>
    <p class="center">【お客様の現在のご予約リクエスト状況】</p>
    <% @users.each do |user| %>
      <table class="table table-bordered table-condensed table-account">
      
        <thead>
          <tr><th colspan="6" class="table-head-2"><%= user.name %> さまからのご予約 [Email: <%= mail_to user.email %> ] [電話番号: <%= user.phone %> ]</th></tr>
        </thead>
        <% @events.each do |event| %>
          <% if event.user_id == user.id %> <%# これでeventのなかで該当するuserのeventだけを表示する  %>
            <thead>
              <tr><th colspan="6" class="table-margin"></th></tr>
              <tr> 
                <th class="table-head-1">ご希望の時間</th>
                <th class="table-head-1">ご希望の内容</th>
                <th class="table-head-1">ご希望のスタイリスト</th>
                <th class="table-head-1">変更</th>
                <th class="table-head-1">削除</th>
                <th class="center" style="background-color: #FFFF00;">リクエスト状況</th>
              </tr>
            </thead>
            <tbody>
              <tr> 
                <td class="center"><%= l(event.started_at, format: :custom) %></td>
                <td class="center"><%= event.title %></td>
                <td class="center"><%= event.selector_stylist_request %></td>
                <td class="center"><%= link_to '変更', edit_event_response_user_path(user, event), remote: true, class: "btn btn-xs btn-primary" %></td>
                <td class="center"><%= link_to '削除', destroy_event_response_user_path(user, event), method: :delete, data: { confirm: '削除してもよろしいでしょうか?' }, class: "btn btn-xs btn-info" %></td>
                <td class="center" style="color: #F00; font-weight: 900;"><%= event.status_event_request %></td>
              </tr>
              <tr>
                <th colspan="5" class="table-head-1">ご要望/通信欄</th>
                <th class="table-head-1">リクエスト状況の更新</th>
              </tr>
              <tr>
                <td colspan="5"  class="center"><%= event.note %></td>
                <td class="center">
                  <%= form_with(model: @event, url: update_request_status_user_path(user, event), method: :patch, local: true) do |f| %>
                    <%= f.select :status_event_request, [['現在リクエスト中'], ['予約受付完了/予約済み'],['内容の変更が必要'], ['保留中'], ['キャンセル完了/取消済み']], { include_blank: true } %>
                    <%= f.submit "更新", class: "btn btn-xs btn-danger" %>
                  <% end %>
                </td>
              </tr>
            </tbody>
          <% end %>
        <% end %>
      </table>
    <% end %>
  <% end %>
</div>


<%# モーダルウィンドウ %>
<div id="user-edit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="user-edit-event-response" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>