config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get "/menus_overview", to: 'static_pages#menus_overview'
  get "/staff", to: 'static_pages#staff'
  get "/map", to: 'static_pages#map'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    omniauth_callbacks: "omniauth_callbacks"
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  resources :users do 

    member do # memberは:idあり
      # GET	/users/:id/edit_event_response
      get "edit_event_response"
      patch "update_event_response"
      delete "destroy_event_response"
      patch "update_request_status"
      # GET	/users/:id/admin_top
      get "admin_top"
      resources :menus
      # GET	/users/:id/admin_events
      get "admin_events"
      get "edit_admin_event_response"
      patch "update_admin_event_response"
      delete "destroy_admin_event_response"
      patch "update_admin_request_status"
    end
    resources :events, except: :show do
      collection do # collectionはevent idなし
        # GET /users/:user_id/events/edit_account_info
        get "edit_account_info"
        # PATCH /users/:user_id/events/update_account_info
        patch "update_account_info"
      end
    end

  end

  
  
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user

  def start_time
    self.started_at
  end

  def end_time
    self.finished_at
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def new
    @event = Event.new
    @menus = Menu.all
    @users = User.where(staff: true).where.not(admin: true) # 担当者全員
    
  end

  def create
    
    @event = Event.new(event_params)
    @event.user = current_user
    if @event.save
      flash[:success] = "予約リクエストに成功しました。"
      redirect_to user_events_path
    else
      flash[:danger] = "予約リクエストに失敗しました。"
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
    @menus = Menu.all
    @users = User.where(staff: true).where.not(admin: true) # 担当者全員
  end

  def update
    @event = Event.find(params[:id])
    
    if @event.update_attributes!(event_params)
     flash[:success] = "予約情報の更新に成功しました。"
     redirect_to user_events_path(current_user)
    else
    flash[:danger] = "予約情報の更新に失敗しました。"
    render :edit
    end
  end

  def show
  end

  def index
    @events = Event.where(user_id: current_user.id).where("started_at >= ?", Date.today).order(started_at: :asc)
    
  end

  def destroy 
    event = Event.find(params[:id]) # paramsにidが入っているので、それを取得してローカル変数に代入する
    event.destroy # ローカル変数に入ったオブジェクトを削除する
    flash[:success] = "予約リクエストを削除しました。"
    redirect_to user_events_path
  end

  def edit_account_info
    @user = current_user
  end

  def update_account_info
    current_user.update_attributes!(user_params)
    flash[:success] = "ユーザー情報を更新しました"
    redirect_to user_events_path(current_user) and return
  rescue
    flash[:danger] = "ユーザー情報の更新に問題がありました"
    redirect_to user_events_path(current_user) and return
  end

  

  private

  

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_edit.html.erb
<div class="modal-dialog modal-md modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>

      <h1 class="modal-title">ご予約の変更</h1>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= form_with(model: @event, url: user_event_path(current_user, @event), local: true, method: :patch) do |f| %>
                
              <%= f.label :title %>
              <%= f.collection_select :title, @menus, :view_item_and_price, :view_item_and_price, class: "form-control" %><br>
              <%= f.label :started_at %>
              <%= f.datetime_select :started_at, { minute_step: 30, start_hour: 9, end_hour: 18 } %>
              <%= f.label :selector_stylist_request %>
              <%= f.collection_select :selector_stylist_request, @users, :name, :name, { include_blank:"希望なし" }, { class: "form-control" } %>
              <%= f.hidden_field :status_event_request, value: "現在リクエスト中" %>
              <%= f.label :note %>
              <%= f.text_area :note, class: "form-control" %>
            
              <%= f.submit "変更", class: "btn btn-md btn-primary" %>
        
              <button type="button" class="btn btn-default btn-info %>" data-dismiss="modal">
                    キャンセル
              </button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_edit_account_info.html.erb
<div class="modal-dialog modal-md modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>

      <h1 class="modal-title">お客様情報の編集</h1>
      <div class="modal-body">
        <div class="container">
          <%= form_with(model: @user, url: update_account_info_user_events_path(current_user), local: true) do |f| %>
            <div class="form-group">
              <%= f.label :control_number %>
              <p><%= current_user.control_number %></p>
            </div>
            <div class="form-group">
              <%= f.label :name %>
              <%= f.text_field :name, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :email %>
              <%= f.text_field :email, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :phone %>
              <%= f.text_field :phone, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :address %>
              <%= f.text_field :address, class: "form-control" %>
            </div>
            
            <%= f.submit "変更", class: "btn btn-md btn-primary" %>
            <%= link_to 'キャンセル', user_events_path(current_user), class: "btn btn-md btn-info" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_new.html.erb
<div class="modal-dialog modal-lg modal-dialog-center">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>

      <h1 class="modal-title">新規ご予約リクエスト</h1>
      <div class="modal-body">
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= form_with(model: @event, url: user_events_path(current_user), local: true, method: :post) do |f| %>
              
              <%= f.label :title %>
              <%= f.collection_select :title, @menus, :view_item_and_price, :view_item_and_price, class: "form-control" %><br>
              <%= f.label :started_at %>
              <%= f.datetime_select :started_at, { minute_step: 30, start_hour: 9, end_hour: 18 } %>
              <%= f.label :selector_stylist_request %>
              <%= f.collection_select :selector_stylist_request, @users, :name, :name, { include_blank:"希望なし" }, { class: "form-control" } %>
              <%= f.hidden_field :status_event_request, value: "現在リクエスト中" %>
              <%= f.label :note %>
              <%= f.text_area :note, class: "form-control" %>
            
              <%= f.submit "リクエスト", class: "btn btn-md btn-primary" %>
        
              <button type="button" class="btn btn-default btn-info %>" data-dismiss="modal">
                    キャンセル
              </button>
              <p></p>
              <p>☆リクエストしてからご予約が確定するまで約1-2日お時間をいただいております☆</p>
              <p>☆リクエスト状況はお客様専用ページでご確認ください☆</p>
            
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/edit.js.erb
$("#event-edit").html("<%= escape_javascript(render 'edit') %>");
$("#event-edit").modal("show");

app/views/events/edit_account_info.js.erb
$("#event-edit-account-info").html("<%= escape_javascript(render 'edit_account_info') %>");
$("#event-edit-account-info").modal("show");

app/views/events/index.html.erb
<%= javascript_include_tag 'application' %>
<h1>お客様専用ページ</h1>

<div>
  <p class="center">【<%= current_user.name%>さんのアカウント情報】</p>
  <table class="table table-bordered table-condensed table-account">
    <thead>
      <tr>
        <th class="table-head-3">管理番号</th>
        <th class="table-head-3">名前</th>
        <th class="table-head-3">Email</th>
        <th class="table-head-3">電話番号</th>
        <th class="table-head-3">変更</th>
      </tr>
    </thead>
    <tbody>
      <tr class="center">
        <td><%= current_user.control_number %></td>
        <td><%= current_user.name %></td>
        <td><%= mail_to current_user.email %></td>
        <td><%= current_user.phone %></td>
        <td><%= link_to '変更', edit_user_registration_path(current_user), local: true, class: "btn btn-xs btn-primary" %></td>
      </tr>
    </tbody>
      <th class="table-head-3">住所</th>
      <td colspan="4" class="center"><%= current_user.address %></td>
  </table>


  <p class="center">☆こちらからご入力ください☆
    <%= link_to '新規ご予約リクエスト', new_user_event_path(current_user), remote: true, class: "btn btn-lg btn-danger" %>
  </p>

  <p></p>
  <p class="center">【リクエスト済み一覧】</p>
    <% @events.each do |event| %>
      <table class="table table-bordered table-condensed table-account">
        <thead>
          <tr>   
            <th class="table-head-1">ご希望の時間</th>
            <th class="table-head-1">ご希望の内容</th>
            <th class="table-head-1">ご希望のスタイリスト</th>
            <th class="center" style="background-color: #FFFF00;">リクエスト状況</th>
            <th class="table-head-1">変更</th>
          </tr>
        </thead>
        <tbody>
            <tr>
              <td class="center"><%= l(event.started_at, format: :custom) %></td>
              <td class="center"><%= event.title %></td>
              <td class="center"><%= event.selector_stylist_request %></td>
              <td class="center" style="color: #F00; font-weight: 900;"><%= event.status_event_request %></td>
              <td class="center"><%= link_to '変更', edit_user_event_path(current_user, event), remote: true, class: "btn btn-xs btn-primary" %></td>
            </tr>
            <td class="table-head-1">ご要望/通信欄</td>
            <td colspan="5"  class="center"><%= event.note %></td>
            
        </tbody>
      </table>
    <% end %>

    <p class="center">☆ご予約リクエストが完了するまでに約1-2日お時間をいただいております☆</p>
    <p class="center">☆ご予約のキャンセルは予約日の2日前までにご連絡をお願いいたします☆</p>
    <p class="center">☆定休日は毎週<font color="red">火曜日</font>です☆</p>
    <div class="container-calendar">
      <%= month_calendar events: @events do |date, events| %>
        <%= date.day %>
        <% events.each do |event| %>
          <%= event.started_at.hour %>:<%= event.started_at.min %>
          <%= event.title %>
        <% end %>
      <% end %>
    </div>

  
  <div class="container">
    <p class="center">☆その他のお問い合わせは<%= mail_to "admin@email.com", "こちら" %>までメールをお願いします☆</p>

    <p class="center">　　　　　</p>
  </div>
</div>
  

<!--モーダルウインドウ表示-->
<div id="event-new" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<div id="event-edit" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

<div id="event-edit-account-info" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/events/new.js.erb
$("#event-new").html("<%= escape_javascript(render 'new') %>");
$("#event-new").modal("show");