config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get "/menus_overview", to: 'static_pages#menus_overview'
  get "/staff", to: 'static_pages#staff'
  get "/map", to: 'static_pages#map'

  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    omniauth_callbacks: "omniauth_callbacks"
  } 

  devise_scope :user do
    get "sign_in", :to => "users/sessions#new"
    get "sign_out", :to => "users/sessions#destroy" 
  end

  resources :users do 

    member do # memberは:idあり
      # GET	/users/:id/edit_event_response
      get "edit_event_response"
      patch "update_event_response"
      delete "destroy_event_response"
      patch "update_request_status"
      # GET	/users/:id/admin_top
      get "admin_top"
      resources :menus
      # GET	/users/:id/admin_events
      get "admin_events"
      get "edit_admin_event_response"
      patch "update_admin_event_response"
      delete "destroy_admin_event_response"
      patch "update_admin_request_status"
    end
    resources :events, except: :show do
      collection do # collectionはevent idなし
        # GET /users/:user_id/events/edit_account_info
        get "edit_account_info"
        # PATCH /users/:user_id/events/update_account_info
        patch "update_account_info"
      end
    end

  end

  
  
end

app/views/layouts/_footer.html.erb
<footer class="footer center">
  <div>
    <small>美容室オレンジ Hair Salon Orange</small><br>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header navbar nabvar-fixed-top">
  <div>
    <%= link_to '美容室オレンジ', root_path, id: "logo" %>

    <div>
      <ul class="nav navbar-nav navbar-center">
        <li><%= link_to 'ホーム', root_url, class: "`nav" %></li>
        <li><%= link_to 'メニュー&料金', menus_overview_path, class: "nav" %></li>
        <li><%= link_to 'スタッフ紹介', staff_path, class: "nav" %></li>
        <li><%= link_to 'アクセス', map_path, class: "nav" %></li>
      </ul>
    </div>

    <div>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? && current_user.admin? %>
          【<%= link_to current_user.name, admin_top_user_path(current_user), { style: "font-size: 16px;" } %>さん】
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-sm btn-info nav-login" %>
        <% elsif user_signed_in? && current_user.staff? %>
          【<%= link_to current_user.name, user_path(current_user), { style: "font-size: 16px;" } %>さん】
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-sm btn-info nav-login" %>
        <% elsif user_signed_in? %>
          【<%= link_to current_user.name, user_events_path(current_user), { style: "font-size: 16px;" } %>さん】
           <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "btn btn-sm btn-info nav-login" %>
        <% else %>
          <%= link_to '新規登録', new_user_registration_path, class: "btn btn-sm btn-info" %>
          <%= link_to 'ログイン', new_user_session_path, class: "btn btn-sm btn-primary"%>
        <% end %>
      </ul>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    

    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="contents">
        <%= render 'shared/flash_messages' %>
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>

  </body>
</html>